### ISSUE TITLE
Ficha Corrientes

### ISSUE THREAD

**Issue by mauriciopasquier** [INTA-Suelos/SiSinta#108]
Nombre tentativo: Formulario Provincia de Corrientes

Cambios necesarios (sólo en la parte de “Analíticos”), que me pasó @dariorodriguez: 
 
1. Donde dice “Carbono Orgánico” agregar una fila arriba de “C %” que diga “MO %”, su valor no se carga, ya que sería una fórmula (= a la celda ya cargada de C% x  1.724). El valor se puede expresar con dos decimales
2. En “Bases intercambiables” agregar una fila que diga “Al+++”: los intervalos de carga serían los mismos que para las otras bases, y el valor expresado igual que las otras
3. Arriba de “Valor S” habría que agregar otra fila que diga “PSI”: su valor tampoco se carga, es una fórmula (=Na+ / Valor T x 100). Na+ y Valor T  ya aparecen y se deben cargar antes. El valor resultante con un decimal
4. Al final de Analíticos: agregar una fila que diga “P ppm” (que sería partes por millón de fósforo) el intervalo de carga sería 0 a 100. El valor se expresa con un decimal

**Comment by dariorodriguez** [comment]
Fui claro Mauricio ? Cualquier cosa avisame

**Comment by Raul-B** [comment]
Bien, estaremos pendientes de los cambios, gracias.

**Comment by mauriciopasquier** [comment]
Esta semana la subo

**Comment by mauriciopasquier** [comment]
Ya está el código, esta noche lo subo al server. Disculpen la demora, tuve algunas complicaciones.

**Comment by dariorodriguez** [comment]
No te preocupes. Como venis con los cobros de las facturas del ministerio ?

**Comment by mauriciopasquier** [comment]
Nunca más se atrasaron, todo bien.

Ya está arriba la ficha, avisenme de cualquier problema en un issue nuevo por favor.
