### ISSUE TITLE
Arenas

### ISSUE THREAD

**Issue by dariorodriguez** [INTA-Suelos/SiSinta#113]
Nos encontramos con un pequeño problema al cargar las arenas en los analíticos. Si bien lo correcto es la clasificación por tamaño que ahora tiene sisinta, algunos laboratorios sólo informan el valor total de las arenas (que sería la sumatoria de todas las fracciones). Sería importante contar entonces con ese campo, que podría realizar automáticamente la suma de todas las arenas, o bien, se podría completar a mano el campo. De nombre llevaría "Arena Total"

**Comment by mauriciopasquier** [comment]
Lo agrego como en blanco mientras decidimos si autocompletarlo o calcularlo vale la pena, principalmente pensando en esta cuestión de datos correctos/útiles/curados vs datos fieles a la planilla.

**Comment by mauriciopasquier** [comment]
Sería para todas las fichas?

**Comment by dariorodriguez** [comment]
Sí, por ahora mejor en blanco, para rellenar a mano. Sería bueno que aparezca el campo donde terminan las arenas, algo así:

Arcilla < 2u	

Limo 2-20u	
Limo 2-50u	

Arena muy fina	
Arena fina	
Arena media	
Arena gruesa	
Arena muy gruesa
Arena Total

**Comment by dariorodriguez** [comment]
Sí, habría que incluirlo en todas las fichas (total, es un campo que si no se completa no pasa nada)

**Comment by dariorodriguez** [comment]
Ya te contesté por el GitHub. Sabés que desde hace unos días no se puede
ingresar la ubicación (lat/long) de los perfiles ? Estuviste tocando eso ?

Sino dejalo como antes que andaba

Abrazo

2016-06-30 6:57 GMT-03:00 Mauricio Pasquier Juan <notifications@github.com>:

> Sería para todas las fichas?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/INTA-Suelos/SiSinta/issues/113#issuecomment-229615376>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACIagMa-OIazhyuQEpNvu3O1cDVqO4Bvks5qQ5MbgaJpZM4JAS25>
> .
>



-- 
Darío

**Comment by mauriciopasquier** [comment]
Sí, toqué algo respecto a la ubicación. Lo arreglo el fin de semana, disculpen.

**Comment by mauriciopasquier** [comment]
Ayer (creo) arreglé lo de las coordenadas. Me confirman?

**Comment by dariorodriguez** [comment]
Sí !!

Gracias capo

2016-07-04 13:44 GMT-03:00 Mauricio Pasquier Juan <notifications@github.com>
:

> Ayer (creo) arreglé lo de las coordenadas. Me confirman?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/INTA-Suelos/SiSinta/issues/113#issuecomment-230325977>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACIagM6I_1-wQNyA4VWfqIQ13XtV8veMks5qSTh2gaJpZM4JAS25>
> .
>



-- 
Darío

**Comment by mauriciopasquier** [comment]
Ya está subido.

**Comment by dariorodriguez** [comment]
Así está bien !

2016-07-06 21:59 GMT-03:00 Mauricio Pasquier Juan <notifications@github.com>
:

> Closed #113 <https://github.com/INTA-Suelos/SiSinta/issues/113>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/INTA-Suelos/SiSinta/issues/113#event-715126101>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ACIagDeu5mtf-TxxA5w7T-Jx_amqmA12ks5qTE92gaJpZM4JAS25>
> .
>



-- 
Darío

**Comment by dariorodriguez** [comment]
Algo como esto podría ser. Esta es una planilla del Instituto de los 90

2016-07-06 21:59 GMT-03:00 Mauricio Pasquier Juan <notifications@github.com>
:

> Closed #113 <https://github.com/INTA-Suelos/SiSinta/issues/113>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/INTA-Suelos/SiSinta/issues/113#event-715126101>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ACIagDeu5mtf-TxxA5w7T-Jx_amqmA12ks5qTE92gaJpZM4JAS25>
> .
>



-- 
Darío

**Comment by mauriciopasquier** [comment]
@dariorodriguez no se qué plantilla decís. Creo que los mails a github no aceptan adjuntos

**Comment by dariorodriguez** [comment]
Que nabo. Te lo mandé por mail. Igual no te preocupes, lo charlamos el
martes

El 7 de julio de 2016, 16:25, Mauricio Pasquier Juan <
notifications@github.com> escribió:

> @dariorodriguez <https://github.com/dariorodriguez> no se qué plantilla
> decís. Creo que los mails a github no aceptan adjuntos
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/INTA-Suelos/SiSinta/issues/113#issuecomment-231181315>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACIagFxZVzgcIQw6FoFGH2dmXdMsskbnks5qTVKMgaJpZM4JAS25>
> .
>



-- 
Darío
