### ISSUE TITLE
Exportar Clase Hz

### ISSUE THREAD

**Issue by mauriciopasquier** [INTA-Suelos/SiSinta#117]
Está faltando este campo en el csv.

**Comment by mauriciopasquier** [comment]
Estuve viendo y no era que faltaba el campo, pero sí estaba mal mostrado. Internamente se llama "Tipo", y me quedó así en la parte de exportar. Ya lo cambié a "Clase".

**Comment by fabiananavarro** [comment]
Buenísimo Mauricio, ya lo vi. Pregunta, es posible cambiar el nombre "clase" por el de "horizonte"? o se complica?
