### ISSUE TITLE
Valores cambiados en las fichas de Corrientes

### ISSUE THREAD

**Issue by Raul-B** [INTA-Suelos/SiSinta#118]
Hola Mauricio, bueno estamos teniendo un problema en la carga de las fichas no sé si son solo las de Corrientes. La cuestion es que cuando se ingresan los datos de los horizonte en forma **parcial**, ej. _hzte, prof, lim, color y textura_. Y luego se pasa a la carga de los **datos analiticos,** al volver y cargar los datos restantes del horizonte. Se altera el **orden** de la presentación de los datos analiticos. Donde el campo _Horizonte_ esta bien pero a partir de _Profundidad_ ya se encuentran alterados de atras hacia adelante se invierten todas las columnas pero los datos siguen estando en su columna correspondiente pero no en el orden que deberian estar. Aclaracion ej. la columna 1 esta en la 6, y la 6 esta en la 1, la 5 en la 2 y la 2 en la 5. Una de las fichas es **Casal CFI 1258**

**Comment by mauriciopasquier** [comment]
Entiendo, gracias por la descripción tan detallada del problema. Ya estoy buscando cómo es que pasa esto.

**Comment by mauriciopasquier** [comment]
Bueno, ya no debería pasar este problema. Te pido que me confirmes cuando prueben con nuevos perfiles.

El problema que queda es qué pasa con los perfiles que ya se cargaron así. Yo no tengo forma de saber si están desordenados, creo que la única opción es revisar uno por uno y corregir los datos "a mano". Disculpen!

**Comment by Raul-B** [comment]
Quedo re bien gracias @mauriciopasquier!
