### ISSUE TITLE
Profundidad máxima del perfil

### ISSUE THREAD

**Issue by guilleschulz** [INTA-Suelos/SiSinta#127]
Buenos días, les escribo por que estoy pasando perfiles de Misiones y me están quedando corto los 10 m de profundidad máxima que tiene Sisinta.

Mauricio, se podrá poner en 20 m? sino me queda información afuera que es una lástima que se pierda.

Gracias.

Guillermo

**Comment by mauriciopasquier** [comment]
Sí, no habría problema. 20 va a estar bien, o saco la restricción directamente?

**Comment by guilleschulz** [comment]
20 va a andar. Gracias

**Comment by mauriciopasquier** [comment]
Ahí aumenté a 20m, disculpá la demora!
