### ISSUE TITLE
latencia en sisinta

### ISSUE THREAD

**Issue by midraed** [INTA-Suelos/SiSinta#72]
Cuando cargo un perfil (en este momento) cuando aprieto "Crear Perfil" se demora en responder entre 15 y 30 segundos. Incluso a veces falla y tengo que volver a presionar el boton. A que se puede deber esa latencia?

Estoy desde la pc de INTA, y fuera del horario de mayor uso de la red (son las 18hs). 
@mauriciopasquier @sbanchero 

Saludos

**Comment by mauriciopasquier** [comment]
Cierro porque ya no pasa (habrá sido cosa de infraestructura de red?)
