### ISSUE TITLE
¿Qué mostrar al clickear en un perfil en el mapa?

### ISSUE THREAD

**Issue by mauriciopasquier** [INTA-Suelos/SiSinta#75]
Actualmente no pasa nada. Podemos mostrar un cuadro con información o llevar directamente a la vista de ese perfil. Si vamos por la primera, decidamos qué poner ahí. La segunda me parece menos redundante. Además, se puede poner información (nombre de serie, número de perfil, etc) a modo de "tooltip" (o sea cuando dejás el cursor sobre un punto) así sabés qué perfil es antes de clickearlo.

¿Qué les parece más práctico?

**Comment by mauriciopasquier** [comment]
Ya está subido, sale un diálogo con link a la serie y al perfil en cada punto.

**Comment by dariorodriguez** [comment]
Excelente !

2015-02-19 19:16 GMT-03:00 Mauricio Pasquier Juan <notifications@github.com>
:

> Closed #75 <https://github.com/INTA-Suelos/SiSinta/issues/75>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/INTA-Suelos/SiSinta/issues/75#event-238746027>.
>



-- 
Darío
