### ISSUE TITLE
Visualizadores espaciales y perfiles publicos

### ISSUE THREAD

**Issue by midraed** [INTA-Suelos/SiSinta#76]
Actualmente tanto en el visualizador de la portada, como en GeoINTA se ven todos los perfiles cargados. Si estos perfiles son privados el usuario podria frustrarse haciendo click en perfiles que solo le avisan que no estan disponibles.

Se deberia poder diferenciar en geoINTA perfiles publicos y perfiles restringidos.
Ademas en el visualiador de la portada de sisINTA la visualizacion podria ser en vez de publicos/rentringidos; ser tengo/no tengo acceso. Dado que tengo acceso incluye publicos y restringidos con acceso.

 Quizas @mauriciopasquier puede implementarlo en el geojson para geoINTA y luego @sbanchero lo adapta en geoINTA.

Esto lo habiamos discutido en #66.

**Comment by mauriciopasquier** [comment]
Quedamos en mostrar sólo los perfiles públicos por ahora, para evitar frustraciones. Más adelante, con la interfaz de "pedir acceso", podemos mostrar todos pero diferenciar visualmente (azul/rojo?) los públicos de los privados.

**Comment by dariorodriguez** [comment]
Eso estaría bueno

**Comment by mauriciopasquier** [comment]
Cierro el issue porque está implementado lo de mostrar sólo los públicos. Si más adelante surge otra necesidad abrimos otro issue.
