### ISSUE TITLE
Carga de perfiles - numero maximo de horizontes = 8?

### ISSUE THREAD

**Issue by guilleschulz** [INTA-Suelos/SiSinta#79]
Buenas, tengo problemas en la carga de datos analíticos, específicamente con el perfil: http://sisinta.inta.gob.ar/perfiles/1226 que tiene 9 horizontes, solo me generó 8 columnas, no se si es el límite máximo de datos que toma el sistema hasta ahora.

Gracias y saludos.

**Comment by midraed** [comment]
Ahora no muestra mas la ficha... si muestra los [analiticos...](http://sisinta.inta.gob.ar/perfiles/1226/analiticos). Mas temprano andaba. 

@guilleschulz te edito un poco el nombre del issue, para que sea mas claro.

**Comment by mauriciopasquier** [comment]
Yo veo bien la ficha.

Técnicamente no hay problema con poner más de 8 horizontes, pero la tabla sí está limitada. Tendríamos que desviarnos de la planilla en papel un poco para que sea lindo y usable

**Comment by midraed** [comment]
Si anda la ficha. Pero descubri un comportamiento extraño.

Si no estoy logueado, no puedo entrar a la ficha.. y me devuelve un error (something wrong ..)
Peroo..  si no estoy logueado, si puedo acceder a los analiticos. Si escribo el link.

Cuando me logueo, anda la ficha perfectamente. Voy a investigar mas y armo un issue para esto.

**Comment by guilleschulz** [comment]
Estaría bueno q genere más de 8 columnas sino van a quedar datos sin cargar

**Comment by midraed** [comment]
Bueno... eventualmente.. y cuando resolvamos #36 podemos verlo de trabajarlo ahi. 

Si @guilleschulz deberia esperar a ese momento para corregir el perfil 1226. Debe ser el unico que tiene >de 8 horizontes.

**Comment by guilleschulz** [comment]
Ok. La parte de cargar 9 horizontes no hubo drama, el problema fue en la tabla de datos analíticos.

Gracias

**Comment by guilleschulz** [comment]
Groso @mauriciopasquier vi, que ya arreglaste lo de la tabla de datos analíticos ;).

Abrazo

**Comment by midraed** [comment]
Excelente. Cierro entonces!
