### ISSUE TITLE
Falta de campo para "gravas"

### ISSUE THREAD

**Issue by guilleschulz** [INTA-Suelos/SiSinta#80]
Habría que agregar otro campo en la planilla de carga de datos analíticos que se llame "Gravas" y tendría que ser en (%) en la parte final de Textura.

En algunas fichas en papel aparece una fila con el campo vacío, normalmente ahí se agregaba a mano en el caso de los suelos que tengan gravas.

Gracias y saludos

**Comment by midraed** [comment]
Estoy que plantea Guille es importante. En Mendoza nunca usamos ese espacio vacio que dice Guille.. y el porcentaje de gravas (o fraccion mayor a 2mm, o esqueleto grueso), terminaba anotado en formaciones especiales.
Al final este dato, es muy importante por ejemplo para estimar el agua disponible. Y entonces creo que hay que formalizar su inclusión. Ademas porque muchas veces esta anotado en algun lugar..

Primero que nada (y para mauricio) es una propiedad del horizonte.
Lo que tenemos que decidir es si es una propiedad analitica (o sea que la medimos en laboratorio en el tamiz) o es una propiedad de campo. Eso va a condicionar que este en la tabla de horizontes, despues de formaciones especiales por ejemplo, o que este en la parte de datos analiticos, despues de las fracciones texturales. 

La realidad es que a veces se estima (a ojo) en campo, y otras veces se mide en laboratorio. Y a veces, se estima a campo y se corrobora en laboratorio. Lo que nos lleva a la peor opcion, para mi, que seria tener que agregar 2 campos: uno de % de gravas a campo y otro en laboratorio.

Creo que podria ser mejor que acordemos, solo agregar el dato analitico.

**Comment by dariorodriguez** [comment]
No está para nada claro este tema. Incluso habría que tener mucho cuidado con el origen de los valores que se ingresan. Como es que se hace en Mza Fede ?
De lo que yo conozco (y en nuestra zona no hay mucho suelos con grava) se indica como "presencia" de gravas o gravillas en uno o más horizontes y a lo sumo se hace una estimación visual del volumen que ocupan las gravas en porcentaje sobre el total del suelo. Pero ojo ! ese porcentaje no se suma a arenas, limos y arcillas, ya que estas últimas deberían sumar 100 % de la muestra ya que se trabaja sólo sobre las partículas menores a 2 mm. Se entiende o me embarullé ?

**Comment by midraed** [comment]
Se entiende. Y si: las fracciones menores a 2mm suman 100%. 
Nosotros, anotamos a ojo, o a veces medido con el tamiz de 2mm, el porcentaje de gravas (de esqueleto grueso le ponemos nosotros). Entonces: luego el calculo de agua disponible se afecta por el porcentaje de esqueleto grueso.

O sea que podemos tener un suelo que tiene 60% de esqueleto grueso, y que luego tiene una composicion de 10% arcilla, 20% limo y 70% arena. Y si el wd es de 20 mm (condirando el espesor total de esa capa/horizonte), el valor final de agua util, que importa agronomicamente es 20 * 0.6

Ahora me embarulle yo.. ja.

**Comment by guilleschulz** [comment]
En los perfiles de Entre Ríos aparecen las 2 opciones que comentaron antes:
- 1: el relevador coloca en la ficha lo que observa a campo y le asigna un % estimativo de presencia y tamaño (por ejemplo 3% de gravas de 0,5 mm).
- 2: existe el dato de laboratorio que se obtiene de las muestras extraídas a campo.

Al no existir la fila en los datos analíticos donde completar este dato muchas veces los terminaba agregando en Observaciones u otro campo como para que no se pierda. El problema es que si se descarga el .csv este dato no se si se descarga.

Abrazos

**Comment by mauriciopasquier** [comment]
No me queda claro al releer la discusión qué campos agregar, dónde y qué valores permitir. Lo subiría junto con lo de arenas (#113).

> En los perfiles de Entre Ríos aparecen las 2 opciones que comentaron antes:
> 
>    1: el relevador coloca en la ficha lo que observa a campo y le asigna un % estimativo de presencia y tamaño (por ejemplo 3% de gravas de 0,5 mm).

Esto iría en la ficha principal? Es genérico del perfil, o va en cada horizonte? Está bien usar Observaciones para esto?

>   2: existe el dato de laboratorio que se obtiene de las muestras extraídas a campo.

Esto iría en Datos analíticos, al final de textura como dice @guilleschulz, no?

**Comment by guilleschulz** [comment]
Mauricio
Creo que lo de % de presencia y tamaño (caso 1) en cada horizonte se podría poner en el campo "formaciones especiales".

El caso 2 es como vos decís, se podría agregar un campo al finalizar Textura en los Datos Analíticos.

Saludos.

**Comment by mauriciopasquier** [comment]
Bueno, entonces por ahora lo agregué a Datos Analíticos nomás. Cualquier cosa avisen por nuevo issue. Ya está subido

**Comment by dariorodriguez** [comment]
Creo que está bien. Igual veamos que dice Fede, ya que por ej Cuyo es zona
de suelos pedregosos

2016-07-06 21:59 GMT-03:00 Mauricio Pasquier Juan <notifications@github.com>
:

> Bueno, entonces por ahora lo agregué a Datos Analíticos nomás. Cualquier
> cosa avisen por nuevo issue. Ya está subido
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/INTA-Suelos/SiSinta/issues/80#issuecomment-230950943>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACIagCGUg-Q88Esc3qDY9tbiKv_TBxP6ks5qTE9WgaJpZM4DaccC>
> .
>



-- 
Darío
