### ISSUE TITLE
servidor lento?

### ISSUE THREAD

**Issue by angelini75** [INTA-Suelos/SiSinta#87]
Hola,
No se si es un problema mío o es general, pero la página (de sisinta) tarda cada vez más en responder y al menos de acá la descarga, selección o consulta de perfiles no funciona. Aparece un mensaje como este
Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request POST /perfiles/procesar.csv.

Reason: Error reading from remote server

Probablemente porque expira el tiempo de espera.

**Comment by mauriciopasquier** [comment]
Buenas! Una consulta: cuándo fue la última vez que pudiste descargar bien? Porque hace rato que no se toca nada en el server

**Comment by mauriciopasquier** [comment]
Me queda la duda de si se había resuelto el #72 o no

**Comment by sbanchero** [comment]
Buenos días, ahí estuve mirando un poco. De red no es el problema. El problema es que la virtual esta hasta las manos. Necesita más RAM. Esta paginando mucho por eso es una tortuga tiene 60 MB de libres de RAM y 400 MB de Swap el resto esta ocupado. @mauriciopasquier  si podes pegale una reiniciada porque ese swap no lo va a liberar nunca más. Digo así revive un poco. Si me das el ok yo lo hago, estoy logueado en la virtual.

**Comment by sbanchero** [comment]
Si vas derecho por la IP sin pasar por el proxy reverso dice esto:
We're sorry, but something went wrong.

We've been notified about this issue and we'll take a look at it shortly.

2015-04-17 8:29 GMT-03:00 Mauricio Pasquier Juan <notifications@github.com>:

> Me queda la duda de si se había resuelto el #72
> <https://github.com/INTA-Suelos/SiSinta/issues/72> o no
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/INTA-Suelos/SiSinta/issues/87#issuecomment-93968789>.
>



-- 
Santiago Banchero

**Comment by midraed** [comment]
Bueno.. dicen que lo van a solucionar, despreocupemonos nosotros:

We've been notified about this issue and we'll take a look at it shortly.





Jejej.. perdon no me pude aguantar la broma. Santi, si mauricio no
responde, la reinicias? Capaz que ya no esta frente a su maquina..




2015-04-17 9:40 GMT-03:00 Santiago Banchero <notifications@github.com>:

**Comment by sbanchero** [comment]
Si, ahí quedó andando de maravillas!
Buen finde muchachos!


El 17 de abril de 2015, 10:48, Guillermo Federico Olmedo <
notifications@github.com> escribió:

> Bueno.. dicen que lo van a solucionar, despreocupemonos nosotros:
>
> We've been notified about this issue and we'll take a look at it shortly.
>
>
>
>
>
> Jejej.. perdon no me pude aguantar la broma. Santi, si mauricio no
> responde, la reinicias? Capaz que ya no esta frente a su maquina..
>
>
>
>
> 2015-04-17 9:40 GMT-03:00 Santiago Banchero <notifications@github.com>:
>
> > Si vas derecho por la IP sin pasar por el proxy reverso dice esto:
> > We're sorry, but something went wrong.
> >
> > We've been notified about this issue and we'll take a look at it shortly.
> >
> > 2015-04-17 8:29 GMT-03:00 Mauricio Pasquier Juan <
> notifications@github.com
> > >:
> >
> > > Me queda la duda de si se había resuelto el #72
> > > <https://github.com/INTA-Suelos/SiSinta/issues/72> o no
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/INTA-Suelos/SiSinta/issues/87#issuecomment-93968789
> > >.
> > >
> >
> >
> >
> > --
> > Santiago Banchero
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/INTA-Suelos/SiSinta/issues/87#issuecomment-93978106
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/INTA-Suelos/SiSinta/issues/87#issuecomment-93989550>.
>



-- 
Santiago Banchero

**Comment by angelini75** [comment]
habilitá mas RAM viejita!!!

2015-04-17 17:17 GMT+02:00 Santiago Banchero <notifications@github.com>:

> Si, ahí quedó andando de maravillas!
> Buen finde muchachos!
>
>
> El 17 de abril de 2015, 10:48, Guillermo Federico Olmedo <

**Comment by angelini75** [comment]
Solucionado
