### ISSUE TITLE
portada no muestra capa OSM

### ISSUE THREAD

**Issue by angelini75** [INTA-Suelos/SiSinta#89]
El mapa en la portada de sisinta no muestra la capa de open street map.

**Comment by midraed** [comment]
Si.. de hecho no se ve. Ayer en realidad no funcionó durante un rato largo
sisinta. Pero hoy puedo entrar y solo tenemos puntos.

**Comment by mauriciopasquier** [comment]
On Thu, Aug 13, 2015 at 04:49:17AM -0700, Guillermo Federico Olmedo wrote:
> Si.. de hecho no se ve. Ayer en realidad no funcionó durante un rato largo
> sisinta. Pero hoy puedo entrar y solo tenemos puntos.

cambiaron la url de los tiles. Ya estoy buscando otra alternativa más estable

--

**Comment by mauriciopasquier** [comment]
En geointa usan los de google maps, no? Uso esos directamente? No hay tiles propios del inta? :P

ping @sbanchero

**Comment by sbanchero** [comment]
No hay tiles de INTA. En geointa.inta.gov.ar/visor usamos gmaps.
Pero en la nueva estamos usando Bing porque en Openlayers 3 hay que
hardcodear mucho para que que funcione gmaps.
¿Qué necesitas una imagen de base y la cartografía de base?
Lo dejo a tu criterio @mauriciopasquier

El 24 de agosto de 2015, 22:18, Mauricio Pasquier Juan <
notifications@github.com> escribió:

> En geointa usan los de google maps, no? Uso esos directamente? No hay
> tiles propios del inta? :P
>
> ping @sbanchero <https://github.com/sbanchero>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/INTA-Suelos/SiSinta/issues/89#issuecomment-134436352>.
>



-- 
Santiago Banchero

**Comment by mauriciopasquier** [comment]
Arreglado esto. Puse dos capas de google (terreno y satélite) y la de datos de open street map, junto con un selector de capas. Se pueden ir agregando capas interesantes si hiciera falta.

De paso, aparecieron unos puntos ubicados en cualquier lado :P
