### ISSUE TITLE
Problema en la carga de un perfil existente (permisos?)

### ISSUE THREAD

**Issue by Raul-B** [INTA-Suelos/SiSinta#91]
Buenas, estamos teniendo el siguiente problema nos a pasado con varios perfiles pero en este momento cito este en particular. El perfil Apipé que lo cargo Rosa Salvadora Lencinas con un usuario Autorizado no lo puede editar le dice que no tiene permisos y no le aparece la opción cuando le da a ver. Pense que podia ser problema de permisos asi que fui a la sección de permisos le asigne el usuario de ella pero quedo todo igual. Con mi usuario de administrador si lo puedo modificar, pero bueno la idea es que lo pueda hacer ella.

**Comment by mauriciopasquier** [comment]
@Raul-B: Ya subí el arreglo para esto, por favor prueben si ahora anda.

**Comment by Raul-B** [comment]
Hola Mauricio, sabes que hoy probamos y sigue todo igual!?

**Comment by mauriciopasquier** [comment]
@Raul-B: Pasame un link al perfil y el email del usuario que intenta cargar, así investigo bien.

**Comment by Raul-B** [comment]
Este es uno,  http://sisinta.inta.gob.ar/perfiles/1257 pero todos los que cargo tienen este inconveniente, al principio no era así, el usuario Rosa Salvadora Lencinas lencinas.rosa@inta.gob.ar Autorizado.

**Comment by mauriciopasquier** [comment]
@Raul-B: puede ser que hayan creado el perfil con otro usuario? Un usuario eliminado?

**Comment by Raul-B** [comment]
No me acuerdo, pero creo que el usuario (Rosa), se habia olvidado la contraseña y no podia restaurarla. Y la verdad ya no recuerdo es probable yo haya eliminado y dado a dar de alta nuevamente con el mismo nombre de usuario.

**Comment by mauriciopasquier** [comment]
Claro, eso me parece. Estoy buscando en los backups para confirmar, pero si fuera así, es normal que no pueda acceder, ya que no es el usuario que cargó el perfil. Sólo los administradores pueden modificar perfiles de otros usuarios o perfiles sin usuario.

Voy a asignarle a Rosa los perfiles y series que había creado con el usuario viejo, así puede editar. Y para evitar que vuelva a pasar algo así, habría que implementar algún mecanismo para que un admin pueda hacerlo desde el sitio (y avisar que al borrar un usuario sus perfiles quedan huérfanos)

**Comment by Raul-B** [comment]
Pero no creo que sea ese el problema por que despues con el usuario nuevo ingresamos datos y creamos fichas nuevas y tenemos el mismo inconveniente.

**Comment by mauriciopasquier** [comment]
Ok, pasame por favor una ficha que hayan creado con el usuario nuevo así investigo

**Comment by Raul-B** [comment]
Ahi estuvimos viendo y si, las nuevas series que cargo con el nuevo usuario andan bien. Esto paso hace unos meses todo comenzo con el tema de que se olvido la clave y no la podiamos restaurar, bueno ahora antes de tomar alguna decisión asi la voy a consultar primero, gracias.

**Comment by mauriciopasquier** [comment]
Bueno, yo acabo de hacer lo que te dije así pueden editar los perfiles viejos. Avisame cualquier cosa.

**Comment by mauriciopasquier** [comment]
@guilleschulz mientras revisaba este issue vi que todos estos perfiles quedaron huérfanos de un usuario tuyo, puede ser? Los asigno a tu nuevo usuario?

* http://sisinta.inta.gob.ar/perfiles/861
* http://sisinta.inta.gob.ar/perfiles/882
* http://sisinta.inta.gob.ar/perfiles/1191
* http://sisinta.inta.gob.ar/perfiles/1192
* http://sisinta.inta.gob.ar/perfiles/1193
* http://sisinta.inta.gob.ar/perfiles/1195
* http://sisinta.inta.gob.ar/perfiles/1196
* http://sisinta.inta.gob.ar/perfiles/1197
* http://sisinta.inta.gob.ar/perfiles/1198
* http://sisinta.inta.gob.ar/perfiles/1199
* http://sisinta.inta.gob.ar/perfiles/1200
* http://sisinta.inta.gob.ar/perfiles/1201
* http://sisinta.inta.gob.ar/perfiles/1202
* http://sisinta.inta.gob.ar/perfiles/1203
* http://sisinta.inta.gob.ar/perfiles/1204
* http://sisinta.inta.gob.ar/perfiles/1205
* http://sisinta.inta.gob.ar/perfiles/1206
* http://sisinta.inta.gob.ar/perfiles/1207
* http://sisinta.inta.gob.ar/perfiles/1208
* http://sisinta.inta.gob.ar/perfiles/1209
* http://sisinta.inta.gob.ar/perfiles/1210
* http://sisinta.inta.gob.ar/perfiles/1211
* http://sisinta.inta.gob.ar/perfiles/1212
* http://sisinta.inta.gob.ar/perfiles/1213
* http://sisinta.inta.gob.ar/perfiles/1214
* http://sisinta.inta.gob.ar/perfiles/1215
* http://sisinta.inta.gob.ar/perfiles/1216
* http://sisinta.inta.gob.ar/perfiles/1217
* http://sisinta.inta.gob.ar/perfiles/1218
* http://sisinta.inta.gob.ar/perfiles/1219
* http://sisinta.inta.gob.ar/perfiles/1220
* http://sisinta.inta.gob.ar/perfiles/1221
* http://sisinta.inta.gob.ar/perfiles/1222
* http://sisinta.inta.gob.ar/perfiles/1223
* http://sisinta.inta.gob.ar/perfiles/1224
* http://sisinta.inta.gob.ar/perfiles/1225
* http://sisinta.inta.gob.ar/perfiles/1226
* http://sisinta.inta.gob.ar/perfiles/1227
* http://sisinta.inta.gob.ar/perfiles/1228
* http://sisinta.inta.gob.ar/perfiles/1230
* http://sisinta.inta.gob.ar/perfiles/1232
* http://sisinta.inta.gob.ar/perfiles/1234
* http://sisinta.inta.gob.ar/perfiles/1235
* http://sisinta.inta.gob.ar/perfiles/1237
* http://sisinta.inta.gob.ar/perfiles/1491

**Comment by guilleschulz** [comment]
Hola Mauricio, si, tampoco sabía eso de que al cambiar de usuario dejabas de poder editarlo. El mail original con el que me había logueado ya no existe más, por eso lo cambié. Pasámelos nomás al usuario nuevo. Gracias.

**Comment by mauriciopasquier** [comment]
@guilleschulz listo!
