### ISSUE TITLE
SiSINTA muy lento / no ingresa usuario

### ISSUE THREAD

**Issue by angelini75** [INTA-Suelos/SiSinta#94]
@mauriciopasquier 
Parece el mismo problema que aparece de tanto en tanto (cahe?)

{Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /.

Reason: Error reading from remote server}

**Comment by mauriciopasquier** [comment]
Puede ser que los servers estén matando la máquina.. voy a tratar de tunearlos esta semana. Igual no vendría mal un poco más de RAM, tiene 1gb ahora el server.

**Comment by mauriciopasquier** [comment]
Ver #104
