### ISSUE TITLE
Error al intentar cargar archivos adjuntos.

### ISSUE THREAD

**Issue by Raul-B** [INTA-Suelos/SiSinta#96]
Hola Mauricio, te consulto el usuario Rosa Salvadora Lencinas lencinas.rosa@inta.gob.ar no puede adjuntar ningun archivo en ninguno de los perfiles, cuando presiona el boton para adjuntar le sale este cartelito: 
"We're sorry, but something went wrong.
We've been notified about this issue and we'll take a look at it shortly."
Sin embargo con mi usuario Administrador, si puedo ¿que puede ser?

**Comment by mauriciopasquier** [comment]
Creo que encontré el error, esta tarde reviso bien.

**Comment by mauriciopasquier** [comment]
Prueben ahora por favor.

**Comment by Raul-B** [comment]
Ahora puede abrir la venta para adjuntar, selecciona el link y cuando le da al boton "crear adjunto", le sale el mismo error

**Comment by guilleschulz** [comment]
Mauricio, este mismo error que menciona Raúl es lo que me sale a mi que te comentaba los otros días. Abrazo

**Comment by mauriciopasquier** [comment]
@Raul-B @guilleschulz prueben ahora por favor

**Comment by Raul-B** [comment]
Quedo de lujo, gracias Mauricio!

**Comment by guilleschulz** [comment]
Anda de diez. Gracias

**Comment by mauriciopasquier** [comment]
Me alegro, gracias por confirmar @Raul-B y @guilleschulz
