### ISSUE TITLE
sisINTA DOWN

### ISSUE THREAD

**Issue by midraed** [INTA-Suelos/SiSinta#99]
Estimados @sbanchero @mauriciopasquier,

sisINTA ha estado caído todo el día. Faltará una reiniciada??

Quedó en nada la mudanza de servidor.. porque quizás eso solucionaría... 

Salute

**Comment by mauriciopasquier** [comment]
Debe ser algo del proxy, porque desde adentro del server funciona.

**Comment by midraed** [comment]
Lo esperamos a Santiago tonces!!

Gracias Mauri

**Comment by sbanchero** [comment]
Buenos días, si efectivamente el reverso está en las últimas. Tuvimos corte
programado de tensión y cuando arranco no pasó la verificación de disco.
Ahora ya está funcionando.

Peeeeero, no andan los DNS de INTA ahora.... no se termina nunca!

Abrazo!
Santiago

El 21 de diciembre de 2015, 23:32, Guillermo Federico Olmedo <
notifications@github.com> escribió:

> Lo esperamos a Santiago tonces!!
>
> Gracias Mauri
>
> El 21 de diciembre de 2015, 23:29, Mauricio Pasquier Juan <
> notifications@github.com> escribió:
>
> > Debe ser algo del proxy, porque desde adentro del server funciona.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/INTA-Suelos/SiSinta/issues/99#issuecomment-166485368
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/INTA-Suelos/SiSinta/issues/99#issuecomment-166485751>.
>



-- 
Santiago Banchero

**Comment by sbanchero** [comment]
Buenos días,
a las 9 hs hay un corte programado, que no se sabe la duración así que voy
a estar apagando todo en unos 10 minutos.

Abrazo
Santiago

El 22 de diciembre de 2015, 9:33, Santiago Banchero <
santiagobanchero@gmail.com> escribió:

> Buenos días, si efectivamente el reverso está en las últimas. Tuvimos
> corte programado de tensión y cuando arranco no pasó la verificación de
> disco. Ahora ya está funcionando.
>
> Peeeeero, no andan los DNS de INTA ahora.... no se termina nunca!
>
> Abrazo!
> Santiago
>
> El 21 de diciembre de 2015, 23:32, Guillermo Federico Olmedo <
> notifications@github.com> escribió:
>
>> Lo esperamos a Santiago tonces!!
>>
>> Gracias Mauri
>>
>> El 21 de diciembre de 2015, 23:29, Mauricio Pasquier Juan <
>> notifications@github.com> escribió:
>>
>> > Debe ser algo del proxy, porque desde adentro del server funciona.
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <
>> https://github.com/INTA-Suelos/SiSinta/issues/99#issuecomment-166485368>.
>>
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/INTA-Suelos/SiSinta/issues/99#issuecomment-166485751>
>> .
>>
>
>
>
> --
> Santiago Banchero
>
>


-- 
Santiago Banchero

**Comment by sbanchero** [comment]
Se suspendió para el lunes 28 a las 9 hs.

Felices fiestas muchachos!

El 23 de diciembre de 2015, 8:31, Santiago Banchero <
santiagobanchero@gmail.com> escribió:

> Buenos días,
> a las 9 hs hay un corte programado, que no se sabe la duración así que voy
> a estar apagando todo en unos 10 minutos.
>
> Abrazo
> Santiago
>
> El 22 de diciembre de 2015, 9:33, Santiago Banchero <
> santiagobanchero@gmail.com> escribió:
>
>> Buenos días, si efectivamente el reverso está en las últimas. Tuvimos
>> corte programado de tensión y cuando arranco no pasó la verificación de
>> disco. Ahora ya está funcionando.
>>
>> Peeeeero, no andan los DNS de INTA ahora.... no se termina nunca!
>>
>> Abrazo!
>> Santiago
>>
>> El 21 de diciembre de 2015, 23:32, Guillermo Federico Olmedo <
>> notifications@github.com> escribió:
>>
>>> Lo esperamos a Santiago tonces!!
>>>
>>> Gracias Mauri
>>>
>>> El 21 de diciembre de 2015, 23:29, Mauricio Pasquier Juan <
>>> notifications@github.com> escribió:
>>>
>>> > Debe ser algo del proxy, porque desde adentro del server funciona.
>>> >
>>> > —
>>> > Reply to this email directly or view it on GitHub
>>> > <
>>> https://github.com/INTA-Suelos/SiSinta/issues/99#issuecomment-166485368
>>> >.
>>>
>>> >
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/INTA-Suelos/SiSinta/issues/99#issuecomment-166485751>
>>> .
>>>
>>
>>
>>
>> --
>> Santiago Banchero
>>
>>
>
>
> --
> Santiago Banchero
>
>


-- 
Santiago Banchero

**Comment by Raul-B** [comment]
Buenos días, sigue caido el servidor? por que desde Corrientes no podemos entrar! alguien sabe que paso?

**Comment by sbanchero** [comment]
Hola Raúl,
estamos con problemas en los AA, no hay refrigeración segura. Así que no se
pueden encender los servidores.
Esto afecta a SISINTA, SIGA y GeoINTA.
Saludos
Santiago

2016-01-04 13:36 GMT-03:00 Raul-B <notifications@github.com>:

> Buenos días, sigue caido el servidor? por que desde Corrientes no podemos
> entrar! alguien sabe que paso?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/INTA-Suelos/SiSinta/issues/99#issuecomment-168726936>.
>



-- 
Santiago Banchero
